name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-dependencies
      with:
        path: |
          $HOME/.pub-cache
          .dart_tool/
          .pub/
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: pub get

    - name: Run tests
      run: pub run test
      